DROP TABLE IF EXISTS METRICS_AGGREGATION_BUCKET;

CREATE TABLE METRICS_AGGREGATION_BUCKET
(
  AGGREGATION_ID  VARCHAR(64)             	NOT NULL,
  START_RANGE     INT                       NOT NULL,
  COUNT           INT                       NOT NULL,
  UNIT_COUNT      INT                       NOT NULL,
  CREATED_FROM    VARCHAR(30)             	NOT NULL,
  UPDATED_AT      DATETIME,
  UPDATED_FROM    VARCHAR(30),
  CREATED_AT      DATETIME
)
TYPE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


CREATE INDEX FK_BUCKET_AGGREGATION_ID ON METRICS_AGGREGATION_BUCKET (AGGREGATION_ID);


alter table METRICS_AGGREGATION_BUCKET
   add constraint FK_AGGREGATION_METRICS_ID foreign key (AGGREGATION_ID)
      references METRICS_AGGREGATION (AGGREGATION_ID);

